name: test
on: [push, pull_request]
jobs:
  install-sh:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sh tests/run.sh
